fixed bugs, added test for RandomGenerator
Savichilya/SecretService pull request #1
Opened 2022-07-11 08:51 UTC by Savichilya

2022-07-11 19:28 UTC, savichmx requested changes

2022-07-11 19:28 UTC, savichmx commented on src/main/java/by/savich/secretservice/service/RandomGenerator.java
> +    public String randomCode(int size){
переименуй в `generateRandomCode`

2022-07-11 19:28 UTC, savichmx commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
> +        assertThat(response.getBody().getSecretInformation()).isNotNull();
Поля `secretInformation` и `passPhrase` можно не проверять на notNull, потому что они у тебя уже через isEqualTo проверяются ниже

2022-07-11 19:28 UTC, savichmx commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
> +
проверь что ещё что у тебя в базе существует Secret по GeneratedCode

2022-07-11 19:28 UTC, savichmx commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
проверь ещё что статус возвращается ОК

2022-07-11 19:28 UTC, savichmx commented on src/test/java/by/savich/secretservice/service/RandomGeneratorTest.java
> +        assertThat(code).isNotNull();
проверь ещё длинну

2022-07-11 19:28 UTC, savichmx commented on src/test/java/by/savich/secretservice/service/SecretServiceTests.java
> +class SecretServiceTests {
`Test` на конце, а не `Tests`

2022-07-12 13:43 UTC, Savichilya commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
для этого же нужно ResponceEntity,  а я его здесь не использую

2022-07-12 13:46 UTC, Savichilya commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
> +
не совсем понял что нужно сделать

2022-07-12 17:25 UTC, savichmx commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
используешь, просто ты тут сразу вызываешь `getBody()`

2022-07-12 17:25 UTC, savichmx commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
> +
проверить что новый secret создался в базе данных

2022-07-15 09:57 UTC, Savichilya commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
вот так можно?
 
 assertThat(this.restTemplate.exchange(host + "/secret/read", HttpMethod.POST,
                httpEntity, new ParameterizedTypeReference<Secret>() {
                }).getStatusCode()).isEqualTo(HttpStatus.OK);

2022-07-15 10:16 UTC, Savichilya commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
> +
а разве вот эта строка не проверяет это?
    assertThat(response.getBody().getGeneratedCode()).isNotNull();

2022-07-15 10:17 UTC, Savichilya commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
> +
если это поле не null, соответственно новый Secret создался

2022-07-15 19:50 UTC, savichmx commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
так ты 2 раза вызываешь свой эндпоинт

2022-07-15 19:51 UTC, savichmx commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
> +
ты проверяешь, что у тебя в ответе эти значения есть. но в теории может быть и такое, что ты эти данные возвращаешь, но в базу не сохраняешь

2022-07-15 20:01 UTC, Savichilya commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
это проблема?
я же не могу так сделать:
assertThat(resultSecret).isEqualTo(HttpStatus.OK);

2022-07-15 20:02 UTC, Savichilya commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
> +
то есть нужно сделать save?

2022-07-15 20:11 UTC, savichmx commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
ну вообще это не совсем правильно, ты можешь просто тут не вызывать getBody сразу
`Secret resultSecret = this.restTemplate.exchange(host + "/secret/read", HttpMethod.POST,
                httpEntity, new ParameterizedTypeReference<Secret>() {
                }).getBody();`
а потом тут уже сделать так` assertThat(resultSecret.getBody).isEqualTo(secret);`

2022-07-15 20:12 UTC, savichmx commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
> +
нет, просто сделать запрос к базе и посмотреть, что эти поля сохранены

2022-07-15 20:50 UTC, Savichilya commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
> +
так можно?
assertThat(secretRepository.findAll()).isNotNull();

2022-07-15 21:52 UTC, savichmx commented on src/test/java/by/savich/secretservice/controller/SecretControllerIntegrationTest.java
> +
ну можно в принципе и так

2022-07-21 17:50 UTC, merged